name: Grocery List

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      name: Build and Test
      runs-on: macos-latest
      strategy:
          matrix:
            destination: ['platform=iOS Simulator,name=iPhone 11']

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run:
             xcodebuild clean build test -resultBundlePath xccov.xcresult -project Grocery\ List.xcodeproj -workspace Grocery\ List.xcworkspace -scheme "Grocery List" -destination "${destination}" -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          env:
           destination: ${{ matrix.destination }}
